services:
  frontend:
    build: ./frontend
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=4000
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    working_dir: /app
    stdin_open: true
    tty: true
    command: npm start

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./data:/data
    environment:
      - JWT_SETCRET=877a819b49d0dde80924127e9f5376634874124f92d03b77171d91d332ae8635
    command: uvicorn app.main:app --host 0.0.0.0 --port 3000 --reload

volumes:
  pgdata:
