services:
  frontend:
    build: ./frontend
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=4000
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    working_dir: /app
    stdin_open: true
    tty: true
    command: npm start

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=db
      - DB_PORT=5432
    command: uvicorn app.main:app --host 0.0.0.0 --port 3000 --reload

  db:
    image: postgres:16
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  pgdata:
